spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
